// Generated by build:templates. This public query exposes only code identity.
import { query } from './_generated/server';
export const version = query({ args: {}, handler: () => ({"providerVersion":"0.0.13","digest":"afa28792ee633fffd13a29d1f1b9ceb9c159e1be62b733878b7f65f5f7df02d2"}) });
